

#==============#
# Camera Model #
#==============#

Camera:
  name: "Pi v3 Monocular"
  setup: "monocular"
  model: "perspective"

  fx: 880.332214
  fy: 882.370020
  cx: 683.323349
  cy: 387.786154

  k1: -0.041063
  k2: 0.050846
  p1: 0.000022
  p2: 0.000714
  k3: 0.000000

  fps: 30
  cols: 1366
  rows: 768

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#========================#
# Initializer Parameters #
#========================#

Initializer:
  scaling_factor: 2.0